import './globals.css'
import type { Metadata } from 'next'
// import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.min.css';
import StoreProvider from './storeProvider'


// const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {


 

  return (
    <html lang="en">
    {/*${inter.className}*/}
      <body className={`bg-body-tertiary `} >
     
          <StoreProvider>
            {children}
          </StoreProvider>
    
      </body>
    </html>
  )
}
